#!/bin/bash

DIR=/home/`logname`
RUBY_VERSION=2.1.3

echo "Installing rbenv and ruby-build"
[[ ! -d $DIR/.rbenv ]] && git clone https://github.com/sstephenson/rbenv.git $DIR/.rbenv
[[ ! -d $DIR/.rbenv/plugins/ruby-build ]] && git clone https://github.com/sstephenson/ruby-build.git $DIR/.rbenv/plugins/ruby-build

PATH=/home/`logname`/.rbenv/bin:$PATH

echo "Setting up rbenv"
eval "$(rbenv init -)"

if [[ ! -d $DIR/.rbenv/versions/$RUBY_VERSION ]]; then
    echo "Installing Ruby $RUBY_VERSION"
    rbenv install $RUBY_VERSION
fi

rbenv version $RUBY_VERSION
rbenv global $RUBY_VERSION
rbenv rehash

gem list --local | grep "bundler" 1> /dev/null
if [[ $? -ne 0 ]]; then
  echo "Installing bundler"
  gem install --no-document bundler
fi
